### ISSUE TITLE
Out of date az.accounts version for PublishADFTask@1

### ISSUE THREAD

**Issue by ludbrookeb** [Azure-Player/azure.datafactory.devops#118]
Hi there :)

As of the mew year I have been running into this

##[error]This module requires Az.Accounts version 2.10.4. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your system. Please see https://aka.ms/azps-version-error for troubleshooting information.

Current version seems to be targeting 2.10.3

**Comment by OlufKelk** [comment]
Am experiencing the exact same issue!

**Comment by AndreaCuneo** [comment]
Same here since yday evening. The issue has been introduced in a version update of the Task.

We're running on Azure Hosted Agent `windows-2022`

This worked fine (v1.15.1261)
```
==============================================================================
2023-01-02T17:18:47.3061559Z Task         : Publish Azure Data Factory
2023-01-02T17:18:47.3061855Z Description  : Deploys entire ADF (v2) from JSON files to ADF instance (adftools)
2023-01-02T17:18:47.3062163Z Version      : 1.15.1261
2023-01-02T17:18:47.3062370Z Author       : Kamil Nowinski (SQLPlayer)
2023-01-02T17:18:47.3062698Z Help         : [More Information](https://github.com/SQLPlayer/azure.datafactory.devops)
==============================================================================

```
This failed (v1.23.1279) with the same error of the OP, 10min after the above.

```
==============================================================================
2023-01-02T17:28:52.3470281Z Task         : Publish Azure Data Factory
2023-01-02T17:28:52.3470593Z Description  : Deploys entire ADF (v2) from JSON files to ADF instance (adftools)
2023-01-02T17:28:52.3470857Z Version      : 1.23.1279
2023-01-02T17:28:52.3471078Z Author       : Kamil Nowinski (AzurePlayer)
2023-01-02T17:28:52.3471406Z Help         : [More Information](https://github.com/Azure-Player/azure.datafactory.devops)
==============================================================================
```

**Comment by edry-jonatan-intellishore** [comment]
Same issue here since yesterday. Unable to publish changes to production as well.

**Comment by inspari-eeth** [comment]
We are experiencing the same issue here.
It could look like, it's one of the modules being imported, other than the Az.Accounts, that is requiring v2.10.4 of Az.Accounts.

We've tried to install Az.Accounts v2.10.4 manually in a PS-task before the ADF-deploy task without luck.

**Comment by OlufKelk** [comment]
Most likely this 0977010cf986f8b78a694c76766902503f973e51 is part of the issues. Az.DataFactory requires v2.10.4 of Az.Accounts.
`$module = Get-Module Az.Accounts 
        if ($module -ne $null -and $module.Version -lt [System.Version]"2.10.3") 
        if ($module -ne $null -and $module.Version -lt [System.Version]"2.10.4")`

**Comment by inspari-eeth** [comment]
Yep, agree.

I don't know if this file needs an update?
![image](https://user-images.githubusercontent.com/104637670/210346249-2bc0f8e3-3a3f-4317-865e-d5c382bc9ae0.png)

**Comment by AndreaCuneo** [comment]
> Yep, agree.
> 
> I don't know if this file needs an update? ![image](https://user-images.githubusercontent.com/104637670/210346249-2bc0f8e3-3a3f-4317-865e-d5c382bc9ae0.png)

I think the whole 'ps_modules' which are the embeeded ones, needs to be updated to v2.10.4, not just this file.

**Comment by inspari-eeth** [comment]
> 

You're probably right! I'm not that much into the PWSH world, so I was just looking through files searching for references to Az.Accounts and something lower than 2.10.4...

**Comment by inspari-eeth** [comment]
> I was looking and seems possible in YAML to request a specific version of a Task, like PublishADFTask@1.15.1261. Unfortunatly we do still use Classic Releases and that is not possible.

Trying to use the specific version in YAML-based pipeline did the trick for me just now: 
![image](https://user-images.githubusercontent.com/104637670/210350725-e3a6915c-2228-4589-be8c-065b88eb422b.png)

`    - task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1.15.1261
`

**Comment by ThomasVanBilsen** [comment]
> > I was looking and seems possible in YAML to request a specific version of a Task, like PublishADFTask@1.15.1261. Unfortunatly we do still use Classic Releases and that is not possible.
> 
> Trying to use the specific version in YAML-based pipeline did the trick for me just now: ![image](https://user-images.githubusercontent.com/104637670/210350725-e3a6915c-2228-4589-be8c-065b88eb422b.png)
> 
> ` - task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1.15.1261`

I tried specifying the version number the same way as you have and run into the following error when executing the pipeline:
![image](https://user-images.githubusercontent.com/5894959/210351816-b576d087-11e7-4f53-b59e-5bb7d3a4f76d.png)

Any idea what could be the issue?

**Comment by inspari-eeth** [comment]
> I tried specifying the version number the same way as you have and run into the following error when executing the pipeline: ![image](https://user-images.githubusercontent.com/5894959/210351816-b576d087-11e7-4f53-b59e-5bb7d3a4f76d.png)
> 
> Any idea what could be the issue?

Did you only change the versionnumber or the entire task reference?

**Comment by ThomasVanBilsen** [comment]
> > I tried specifying the version number the same way as you have and run into the following error when executing the pipeline: ![image](https://user-images.githubusercontent.com/5894959/210351816-b576d087-11e7-4f53-b59e-5bb7d3a4f76d.png)
> > Any idea what could be the issue?
> 
> Did you only change the versionnumber or the entire task reference?

I changed it from:

- task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1

to:

- task: SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1.15.1261

**Comment by sebastien-fauvel** [comment]
Same issue here, and no way to use another version than 1.*

By the way, @NowinskiK, what happened to this new version 1.23.1279? I can't see it in the tags / release list on GitHub. Have you removed it? How can we have Azure DevOps use the previous version again?

**Comment by some1random1991** [comment]
We are experiencing the same issue in multiple tenants. Is there a known workaround that works for classic pipelines? The interface provides version 0.* as an option for us, but sadly we do need several features from version 1.*

**Comment by NowinskiK** [comment]
I'm going to release new fixed version in the next hour. Bear with me.

**Comment by NowinskiK** [comment]
The version of `az.accounts` has been updated and new version (1.24) released. 
This bug should be resolved now. Sorry for inconvenience.
https://github.com/Azure-Player/azure.datafactory.devops/releases/tag/v1.24
