### ISSUE TITLE
Publish-AdfV2FromJson trimming white spaces in sql queries part of Source Data

### ISSUE THREAD

**Issue by nikhil-rajan-neu** [Azure-Player/azure.datafactory.devops#120]
Using the PowerShell comands  on an ubuntu machine to deploy ADF directly from JSON

`- task: PowerShell@2
            enabled: true
            inputs:
              targetType: 'inline'
              script: |
                Install-Module Az.DataFactory -MinimumVersion "1.10.0" -Force
                Install-Module -Name "azure.datafactory.tools" -Force
                Import-Module -Name "azure.datafactory.tools" -Force
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Test-AdfCode -RootFolder .
          - task: AzurePowerShell@5
            enabled: true
            inputs:              
              azureSubscription: 'AMN_Shared_Dev_Staffing_dev'
              ScriptType: 'InlineScript'
              azurePowerShellVersion: 'LatestVersion'
              pwsh: true
              Inline: |
                  $opt = New-AdfPublishOption
                  $opt.Excludes.Add("integrationruntime.*", "")
                  $opt.Excludes.Add("triggers.*", "")
                  $opt.StopStartTriggers = $false
                  Publish-AdfV2FromJson -RootFolder . -ResourceGroupName '$(SharedRGName)' -DataFactoryName '$(DataFactoryName)' -Location '$(location)' -Stage '$(System.DefaultWorkingDirectory)/deployment/adf-config1.json' -Option $opt -Verbose` 
          

After the deployment our Pipelines stopped working 

Looking at the source data , we see the whitespaces have been trimmed 

![image](https://user-images.githubusercontent.com/81550847/210386341-4a9cc639-765e-445c-9264-dd2ce6bca74b.png)

We moved to use the PowerShell commands instead of using the ADO tasks to support linux build agents

**Comment by danielmadison84** [comment]
We experienced this with az_9.2.0 module in Powershell as of January 12 2023. My team found a temporary resolution, switching ubuntu-latest to ubuntu-18.04 in your YML file lets you use az_9.0.1 previous version that does not have this issue.

**Comment by NowinskiK** [comment]
https://github.com/Azure-Player/azure.datafactory.tools/issues/265
