### ISSUE TITLE
New SynapseNotebook activity type throws an error

### ISSUE THREAD

**Issue by LiquoriChris** [Azure-Player/azure.datafactory.devops#121]
Hello, 

We are using the new SynapseNotebook activity in our ADF and when we are trying to deploy the ADF into live mode. We are receiving the following error:

`##[error]The property 'Success' cannot be found on this object. Verify that the property exists.`

Looking into the activity, the referenceName is a dictionary and not a string value.

```
"notebook": {
                        "referenceName": {
                            "value": "<notebook name>",
                            "type": "Expression"
                        },
                        "type": "NotebookReference"
```

Compared to a linkedService reference:
```
"linkedServiceName": {
                    "referenceName": "<linked service name>",
                    "type": "LinkedServiceReference"
                }
```

Digging further, `AdfObject.class.ps1` does not have the following type: `notebook`

```
Line |
  91 |              throw "ADFT0029: Unknown object type: $Type."
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ADFT0029: Unknown object type: Notebook.
```

This is a new activity Microsoft has release within the last few weeks and just making aware of the issue.

Thank you.

**Comment by NowinskiK** [comment]
It looks like this new feature (activity) is not supported atm. Thanks for raising this.

**Comment by NowinskiK** [comment]
Released in ver.1.25.1302
