### ISSUE TITLE
ADF Credentials are not supported to allow configuration via csv

### ISSUE THREAD

**Issue by scott-bellis** [Azure-Player/azure.datafactory.devops#122]
When trying to configure "credentials" in ADF the tool is reporting credentials is not a supported type in the current version. Is there an item to include credentials in future release?

e.g. 
##[error]ADFT0015: Type [credential] is not supported.

**Comment by NowinskiK** [comment]
Credentials are not supported by the tool because Microsoft doesn't support this type of object for API & PowerShell module:
https://github.com/Azure-Player/azure.datafactory.tools#known-issues
Similar thread: https://github.com/Azure-Player/azure.datafactory.tools/issues/156
