### ISSUE TITLE
Validates all JSON files of ADF failed for special character

### ISSUE THREAD

**Issue by dzfstephen** [Azure-Player/azure.datafactory.devops#123]
hello Kamil ,

we are using this to validate and deploy into different environment. We are receiving the following error when it validate the Json files:
##[debug]BEGIN: Get-ReferencedObjects(obj=AdfObject)

##[debug]At line:1 char:28
##[debug]+ $in = $node.'RFP's Involved'
##[debug]+                            ~
##[debug]The string is missing the terminator: '.
##[debug]   at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
##[debug]   at System.Management.Automation.ScriptBlock.Create(ExecutionContext context, String script)
##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]At line:1 char:18

Any suggestions for this issue. 

Thanks & Regards

**Comment by NowinskiK** [comment]
Should I guess...?

**Comment by NowinskiK** [comment]
No example, no way to replicate the issue. Can't help.
