### ISSUE TITLE
Question: Managed VNET and Managed Private Endpoint

### ISSUE THREAD

**Issue by julanih** [Azure-Player/azure.datafactory.devops#134]
Hi this isn't an issue but i cannot look a question's section.

Well, my question is: Can you explain how it works the taks Publish with the new! feature for Managed VNET and Managed Private Endpoint, y so find in the documentation (README.md) and not found any ideas for use it.

Thanks for your help.
Regards.

**Comment by NowinskiK** [comment]
Could you precise what do you mean by "how it works"?

**Comment by julanih** [comment]
Thanks for you soon reply @NowinskiK,

I have a managedPrivateEndpoint and I need to change the values for some properties like a privateResourceId for example when I deploy to my differents environments, I'll try using environment.cvs but always got the same error "Config file, Type is not supported"

**Comment by NowinskiK** [comment]
Got it. So, describe your problem more precisely, I mean: copy/paste config file and part of log with the (exact) error. 
Managed VNET & Private Endpoints are supported, so probably you configured something incorrectly.

**Comment by julanih** [comment]
hi @NowinskiK I resolved my problem, just for let you know and knowledge to others, in the documentation tells column type does't include VNET and Private Endpoint as a valid type option so I was try with "maganagedVirtualNetwork/default/managedPrivateEndpoint", "managedVirturlNetwork.default.managedPrivateEndpoint" and this got me the error.

Then i kept digging into your issues and commits and found an example with type "managedPrivateEndpoint" and that solved my problem.

![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/5513292/1e664367-8bc1-464c-b18a-8d381626a0d9)

![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/5513292/01783f92-0636-4126-8ce4-0f62703934ae)

Could you update the documentation please.
Thanks for your support!

**Comment by NowinskiK** [comment]
Ahhhh, you checked documentation on DevOps project.... 
Sorry for confusing... the always up-to-date documentation is in this repo:
https://github.com/Azure-Player/azure.datafactory.tools

where you'll see:
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/25029325/315d5250-9397-4372-aef8-6baa338f9a08)

and examples:
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/25029325/4b38d6f2-89ea-4a3f-bc08-adafe7a11695)

I will remove the copy of documentation from here and add links to the correct location.

**Comment by julanih** [comment]
Thanks a lot @NowinskiK five stars service 🥇
