### ISSUE TITLE
Entry Point Not found

### ISSUE THREAD

**Issue by GSC977** [Azure-Player/azure.datafactory.devops#137]
While publishing ADF from Json file we are getting below error.

2023-05-15T15:35:48.4086098Z ##[error]Entry point was not found.
2023-05-15T15:35:48.6191647Z ##[error]There was an error with the service principal used for the deployment.

With the exception of Publish ADF from Json File, the same service principal connection used for other tasks is functional in other deployment tasks.  

<img width="716" alt="image" src="https://github.com/Azure-Player/azure.datafactory.devops/assets/55589395/04d69049-7d72-4eb4-a3d4-cc965622d7bb">

**Comment by dayalus** [comment]
We're getting the same error. We were not getting this with 1.27.1315

**Comment by GSC977** [comment]
> We're getting the same error. We were not getting this with 1.27.1315

Any solution .?

**Comment by DannyvB** [comment]
We are also having this issue, unable to fix it so far

**Comment by GSC977** [comment]
@NowinskiK  can you please check and provide some update or solution on above error/Issue..

**Comment by GSC977** [comment]
did anyone get solution..? @DannyvB @dayalus .. @NowinskiK can you please guide on this issue

**Comment by GSC977** [comment]
@NowinskiK Any update..??

**Comment by NowinskiK** [comment]
Do you use Microsoft (Hosted) Agent or custom DevOps agent?
Everything works with Hosted Agent.

Try to use previous version temporally and check if that works:
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/25029325/80d125ab-5dc7-4d6e-bdcd-301dd61313d4)

It's probably due to update of `Az.Accounts` to ver. 2.12.1 (from )

**Comment by dayalus** [comment]
Same with us..


Best Regards,
Dayal.

**Comment by GSC977** [comment]
how to use specific version in a classic editor pipeline

**Comment by govindareddy0** [comment]
@NowinskiK , Could you please help oh how to use the previous version in Classic editor pipeline. Currently all our releases are impacted with the issue.

**Comment by dayalus** [comment]
Same issue with us - classic editor pipeline. We can only view the YAML

**Comment by NowinskiK** [comment]
I released new version 1.29 which contains 2 upgraded Microsoft Az modules.
Hopefully this will resolve the issue.

**Comment by michasacuer** [comment]
@NowinskiK We have the same issue with Version      : 1.29.1369 as from OP

**Comment by govindareddy0** [comment]
check az.accounts version in devops agent machine and upgrade it to latest version 2.12.2 through powershell
it resolves the issue

**Comment by jessehouwing** [comment]
For those of you hit by this problem and wondering how to deal with such issues in UI based pipelines, releases and where the older version may have been deleted fromt he collection by an uninstall/reinstall of the extension in an attempt to fix the issue:

https://jessehouwing.net/azure-pipelines-you-broke-our-pipeline/

**Comment by dayalus** [comment]
@NowinskiK - we're still having the issue

**Comment by NowinskiK** [comment]
There is nothing else I can do. Your Agent/VM has incompatible PS modules which must be upgraded (described above).

**Comment by jessehouwing** [comment]
It might make sense to query the incompatible version and log a meaningful error instead of letting it throw a method not found exception...

**Comment by dayalus** [comment]
@NowinskiK - thank you! There was an issue with our upgrade. After the upgrade, it now works. Sorry about that!
