### ISSUE TITLE
No Detailed error message while deploying data factory

### ISSUE THREAD

**Issue by jagdish0909** [Azure-Player/azure.datafactory.devops#145]
Hello, 
We are getting only data exception error message while deploying the code using release. Please check below screen shot for more details. 
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/55339805/b180695e-8684-4bef-9e56-698b51411be1)

**Comment by NowinskiK** [comment]
Did you enable Diagnostic/debug log to see more details?
