### ISSUE TITLE
DevOps Extension including v1.5.0 of datafactory tools

### ISSUE THREAD

**Issue by stephennaughton** [Azure-Player/azure.datafactory.devops#146]
Hello,

I wonder if you have any timeframe for the release of an updated version of the Azure DevOps extension which will include the latest 1.5.0 version of azure.datafactory.tools dependency?

https://github.com/Azure-Player/azure.datafactory.tools/releases/tag/v1.5

Thanks,
Stephen

**Comment by NowinskiK** [comment]
Yes, it should be next week.

**Comment by stephennaughton** [comment]
That sounds great. Thanks for the update.
