### ISSUE TITLE
Update global parameters fails for Azure Government subscription

### ISSUE THREAD

**Issue by cog-adf** [Azure-Player/azure.datafactory.devops#148]
**Describe the bug**
I'm receiving a 404 (Subscription not found) when the task is trying to update the global parameters.

**To Reproduce**
Run the pipeline to deploy/update an ADF instance to a subscription hosted in Azure Government which contains global parameters.

GlobalParam.ps1 contains a hardcoded reference to https://management.azure.com (= Azure commercial URL)
The Azure Government URL equivalent is https://management.usgovcloudapi.net

**Expected behaviour**
The parameters are updated without any issues/errors.

**Screenshots**
![2023-07-26 14_22_22-Azure Data Factory - Release-15 - Pipelines](https://github.com/Azure-Player/azure.datafactory.tools/assets/139209030/d415b2de-4600-4a78-8ea4-61d4177daeb1)

**Comment by NowinskiK** [comment]
Duplication of https://github.com/Azure-Player/azure.datafactory.tools/issues/356
