### ISSUE TITLE
Does this ADF devops extension work with both Repository Type provided by Azure i.e. Azure DevOps Git as well as Github Enterprise? If we want to use Github Enterprise for storing all the ADF code, can we still use this extension?

### ISSUE THREAD

**Issue by himanshudbagupta** [Azure-Player/azure.datafactory.devops#150]

**Comment by NowinskiK** [comment]
You can keep the code wherever you want - it has nothing do to with the extension. 
If you want to deploy the code within the extension - it is compatible with Azure DevOps.
However, you can use PowerShell module of #adftools and execute publish using PS from any tool support PowerShell.
