### ISSUE TITLE
"The current operating system is not capable of running this task" error

### ISSUE THREAD

**Issue by zavalajb** [Azure-Player/azure.datafactory.devops#153]
Hi, I'm triying to use the task SQLPlayer.DataFactoryTools.PublishADF.PublishADFTask@1 in a self hosted linux agent but I get the following error "The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell. " I'm using the module azure.datafactory.tools version 1.8,  I understand that this task should works for linux agents. Are there any other powershell modules or extra configurations that should be considered?

![error](https://github.com/Azure-Player/azure.datafactory.devops/assets/129464652/05a0e191-4fdb-4166-bb7b-fa652ebb7403)

**Comment by NowinskiK** [comment]
This was explained in https://github.com/Azure-Player/azure.datafactory.devops/issues/64
