### ISSUE TITLE
Authentication via WorkloadIdentityFederation

### ISSUE THREAD

**Issue by aj4314** [Azure-Player/azure.datafactory.devops#154]
Hi Kamil,

I recently implemented the publish tool for a CICD pipeline running in Azure Devops and it was very smooth. Thanks for your hard work!

I have a quick question in regards to authentication methods when implementing through Azure Devops. Currently it seems that only the service principle approach or managed service identity works - I tried setting up a service connection using Workload Identity federation and encountered this error:
![image (6)](https://github.com/Azure-Player/azure.datafactory.tools/assets/84943448/45da90e3-79e1-4fa5-8c1f-35bde2776c8d)

Since Azure is now recommending workload identity federation are there any plans to make different authentication approaches viable? My company is trying to move away from managing service principles and having to recycle secrets.

Kind regards!

**Comment by NowinskiK** [comment]
Error message (for searchability):
`##[error]Unsupported authentication scheme 'WorkloadIdentityFederation' for Azure endpoint.`

**Comment by timSchw** [comment]
Hi @NowinskiK,
any progress on this?
We're having the same issue.

**Comment by ursu123** [comment]
Hi, we are experiencing the same issue. We would love to use the recommended authentication method for it - as a workaround we reverted to a SP auth.

**Comment by NowinskiK** [comment]
I hope very soonish...

**Comment by NowinskiK** [comment]
Good news: I finally overcame all obstacles and errors related to the development of this feature.
Currently, it's in tests. If you want to have access to Private Preview let me know. It should be deployed in a few days.

**Comment by NowinskiK** [comment]
Released in [v.1.34](https://github.com/Azure-Player/azure.datafactory.devops/releases/tag/v1.34)

**Comment by NowinskiK** [comment]
This feature has been reverted from ver.1.x and released in a new major version [2.0](https://github.com/Azure-Player/azure.datafactory.devops/releases/tag/v2.0), due to backwards incompatibility of related Az.* modules. (Issue #164)
