### ISSUE TITLE
return to the original state when task fails 

### ISSUE THREAD

**Issue by ederfdias** [Azure-Player/azure.datafactory.devops#155]
When I run the pipeline and the task fails for any reason the triggers on the data factory that will be deployed keep stopped.

There is a way to return the data factory to original state?

**Comment by NowinskiK** [comment]
No, there is no way to return to the previous state with the same set of objects.
What you can do is redeploy from the previous version of your (working) code.
I assume you built a **Build pipeline** which generates and versiones all your ADF artifacts before you start deploying them.
If you're not sure how to do that, check out my YouTube channel and this playlist:
[Kamil Data Geek - Azure explained](https://www.youtube.com/@KamilNowinski) / [ADFTools playlist](https://www.youtube.com/playlist?list=PLcW0jJygu-2e2_yZlFSsN2_jNUBmXMMSq)
