### ISSUE TITLE
Deploy Azure Data Factory (#adftools) request 

### ISSUE THREAD

**Issue by ioannisprataris** [Azure-Player/azure.datafactory.devops#160]
Who is the expected requested time of "Deploy Azure Data Factory (#adftools)" for extension of azure devops organization?

**Comment by NowinskiK** [comment]
Sorry, I do not get your question...? If you requested the extension to be installed in your organisation, someone who has appropriate permissions must approve it in Azure DevOps: 
https://dev.azure.com/sqlplayer/_settings/extensions

One will see awaiting extensions on the "Requested" list: 
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/25029325/911c8880-6114-4ef7-8386-c8c5f4bf8e1d)

**Comment by ioannisprataris** [comment]
Thanks
