### ISSUE TITLE
New version break CD as require Az.Accounts v3.0.0

### ISSUE THREAD

**Issue by MasterKuat** [Azure-Player/azure.datafactory.devops#164]
Error : 
This module requires Az.Accounts version 3.0.0. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your system. Please see https://aka.ms/azps-version-error for troubleshooting information.

Please allow task to run ealier Az.Accounts version OR publish a separate version of this task so we can select task version accurate to our environnement. (Ie     "version": "2.00.0000" ?)

**Comment by hatcherdw** [comment]
We ran into the same issue. Dropping back to version 1.32.1423 worked.

**Comment by MasterKuat** [comment]
Hi @hatcherdw would you share your downgrade procedure please ?

**Comment by NowinskiK** [comment]
Why can't you update `Az.Accounts` to the latest 3.0 version?
Az libraries are being updated within almost every deployment of this extension, so it wouldn't be possible to create a new major version every time. What agent do you use?

**Comment by MasterKuat** [comment]
Hi @NowinskiK , cause of this : https://github.com/Azure/azure-powershell/issues/21647. and lot of constraint.
We are using self hosted agent, so we fully control our environment.

Could it be possible for you to set the task version to v2 ? So people who want the new version will able to switch and other, like us, no ;)

Thanks

**Comment by PtrckGdwn** [comment]
We are experiencing that same issue as @MasterKuat and using the same resolution as @hatcherdw. 

We are unable to easily update our agents to use the new Az.Accounts version because this may negatively affect a lot other non-ADF related pipelines that use them. 

Having an @2 version of the task as @MasterKuat suggests would be excellent.

**Comment by MasterKuat** [comment]
@PtrckGdwn @hatcherdw Are you using YAML pipeline, because I'm using classical release pipeline and I do not find a way to specify a full version number. 
No (good) choice.

**Comment by PtrckGdwn** [comment]
@MasterKuat YAML pipelines.

**Comment by NowinskiK** [comment]
Hello all. Sorry for inconvience. 
I can confirm that the workaround for using a specific version of any extension is possible within YAML format.
I will start looking at how to revert the previous version to 1.* and create a new version 2.*

**Comment by svenchio** [comment]
> We are experiencing that same issue as @MasterKuat and using the same resolution as @hatcherdw.
> 
> We are unable to easily update our agents to use the new Az.Accounts version because this may negatively affect a lot other non-ADF related pipelines that use them.
> 
> Having an @2 version of the task as @MasterKuat suggests would be excellent.

I had the same issue, we are using self-hosted agents and it takes some time to get powershell modules updated, but you can specify the specific version directly in your yaml task like this ... hope it helps. 

![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/172777123/2abe4dc1-e5b0-4c86-9d4e-e2a1277d46cf)

**Comment by NowinskiK** [comment]
Thanks @svenchio for additional details and screenshots. Definitely helpful for teams who are impacted.
Unfortunately demanding particular version is available in YAML pipelines ONLY - you can't do that in Classic UI of Release Pipeline.

**Comment by NowinskiK** [comment]
Version 1.35 is now released again with content from ver.1.33 and contains the following Az modules:
- Az.Accounts 2.12.2
- Az.Resources 6.6.1
- Az.DataFactory 1.16.13

If you need the newest version of any of these modules - use ver.2.x.
Thank you for being so patient - please remember that I do this for free in my free time for the Community.
If you appreciate this effort - please [Write a review](https://marketplace.visualstudio.com/items?itemName=SQLPlayer.DataFactoryTools&ssr=false#review-details) of the tool.

**Comment by PtrckGdwn** [comment]
Thanks very much for the prompt turn around @NowinskiK, much appreciated

**Comment by MasterKuat** [comment]
Thank you. But seems version 1.35 was not installed as you publish v2 
![image](https://github.com/Azure-Player/azure.datafactory.devops/assets/48821872/d108bfec-1d6e-4ac4-b3ca-91e29247e8dd)

**Comment by NowinskiK** [comment]
I can publish only one main version of DevOps Extension and the version must increase every time.
Hence, version 2.0.1514 contains two versions of some tasks: 1.x and 2.x - in the classical pipeline, you can choose which one you gonna use.
