### ISSUE TITLE
Anything equivalent to run in Github actions existing?

### ISSUE THREAD

**Issue by DrKabum** [Azure-Player/azure.datafactory.devops#166]
Hi, this issue is more of a general question: Are you aware or have you worked on some Github Actions that would be an equivalent to azure.datafactory.devops? I'm conscious that this is probably not the right place to ask about this, but also the Azure-Player organisation seems very active and might already have an alternative to offer (I couldn't find any from googling and looking into the org repos though)

>[!NOTE] 
> A note of context: we have been using this task for a while in Azure DevOps. We have migrated our repositories to Github but are still running our CI/CD in ADO while we are refactoring our pipelines in Github actions. Currently, our ADF code is being deployed using `Azure-Player/azure.datafactory.devops`, in particular `PublishADFTask` from JSON and we are looking for options for replacement in that context.

Thanks for looking into my question.

**Comment by NowinskiK** [comment]
On the contrary: this is the perfect place to ask such a question.
Unfortunately, there is no dedicated task/template for GitHub Actions. 
However, you can use PowerShell task and execute `Publish` cmdlet from `azure.datafactory.tools` module. 
That would be the easiest alternative.
