### ISSUE TITLE
latest version update, incremental deployment no longer works

### ISSUE THREAD

**Issue by leandroninja** [Azure-Player/azure.datafactory.devops#171]
Hello, I would like to know if after the latest version update, incremental deployment no longer works? Before this latest update, my deployment took about 14 minutes, now it takes 29.30 minutes.
I thank you in advance.

**Comment by NowinskiK** [comment]
It works but in a different way. You must configure a storage to keep deployment state file. 
Check out the documentation: [Incremental Deployment](https://github.com/Azure-Player/azure.datafactory.tools?tab=readme-ov-file#incremental-deployment)
